[workspace]
resolver = "2"
members = ["client", "server", "shared", "xtask"]

[patch.crates-io]
# bonsaidb = { path = "../bonsaidb/crates/bonsaidb" }
bonsaidb = { git = "https://github.com/khonsulabs/bonsaidb.git", branch = "release" }
