[package]
name = "minority-game-shared"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2021"
description = "The shared types of a simple example using a BonsaiDb server backend."
license = "MIT OR Apache-2.0"
publish = false

[features]
actionable-traits = []

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
actionable = "0.1.0"
bonsaidb = "0.1.0"
